### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by mihrab34**

### CODE REVIEW

**Comment by samgaco** [comment]
#### Hi :hand: 

#### Everything is looking good now. Final things before the approval:

* Correct the linters failing checks.
* You still have one small error. Check it out in the [validator](https://validator.w3.org) by uploading the html file.

#### Please :pray:  Correct these issues and submit back for another code review :+1: 

------

* [ SUGGESTION ] Read about [git flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) and implement it moving forward in your next projects. (Try to have all your work in just one pull request )

**Comment by mihrab34** [comment]
@samgaco Do you suggest just one branch and pull request should be used for our next project?

**Comment by samgaco** [comment]
> @samgaco Do you suggest just one branch and pull request should be used for our next project?

Hi. Yes, that is a suggestion for your next projects :+1:

**Comment by samgaco** [comment]
## The project is approved :heavy_check_mark:  

#### You may merge to the master branch now and submit the project completion form :+1: Regards!

**Pull request merged**
